const names = require("./2-names")
const welcome = require("./3-sayHi")
const exportMethods = require("./6-differentExportModules")
require("./4-mindGranade")
console.log(exportMethods)
// welcome(names.john)
// welcome(names.mike)